version: '2'
services:

  database:
    image: thewillonline/newznab-mariadb:latest
    restart: unless-stopped
    volumes:
      - $PWD/data/var_lib_mysql:/var/lib/mysql
      - $PWD/data/etc_mysql_conf.d:/etc/mysql/conf.d
      - $PWD/data/mysql_user:/mysql_user
    environment:
      - MYSQL_ROOT_PASSWORD=newznab
      - MYSQL_DATABASE=newznab
      - MYSQL_USER=newznab
      - MYSQL_PASSWORD=newznab
    expose:
      - "3306"

  newznab:
    image: thewillonline/newznab:latest
    restart: unless-stopped
    ports:
      - 8869:80
    env_file:
      - $PWD/etc/simply_newznab.conf
    volumes:
      - $PWD/data/nzb:/var/www/newznab/nzbfiles
      - $PWD/data/covers:/var/www/newznab/www/covers
      - $PWD/data/sphinx/lib:/sphinxdata

  adminer:
    image: clue/adminer
    restart: unless-stopped
    ports:
      - 8880:80

  sphinxsearch:
    image: thewillonline/newznab-sphinxsearch:latest
    restart: unless-stopped
    volumes:
      - $PWD/data/sphinx/:/opt/sphinx/index
      - $PWD/data/sphinx.conf:/opt/sphinx/conf/sphinx.conf
      - $PWD/data/sphinx/pid/:/var/run/sphinxsearch/
      - $PWD/data/sphinx/logs/:/var/log/sphinxsearch/
      - $PWD/data/sphinx/lib/:/var/lib/sphinxsearch/data/
    ports:
      - 127.0.0.1:36307:36307
#      - 127.0.0.1:9312:9312
#      - 127.0.0.1:9306:9306
  #
  # znc:
  #   image: ghcr.io/linuxserver/znc
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #   volumes:
  #     - $PWD/data/znc/:/config
  #   ports:
  #     - 6501:6501
  #   restart: unless-stopped
