version: '2'
services:

  database:
    image: thewillonline/nzedb-mariadb:latest
    restart: unless-stopped
    volumes:
      - $PWD/data/var_lib_mysql:/var/lib/mysql
      - $PWD/data/etc_mysql_conf.d:/etc/mysql/conf.d
      - $PWD/data/mysql_user:/mysql_user
    environment:
      - MYSQL_ROOT_PASSWORD=nzedb
      - MYSQL_DATABASE=nzedb
      - MYSQL_USER=nzedb
      - MYSQL_PASSWORD=nzedb
    expose:
      - "3306"

  nzedb:
    image: thewillonline/nzedb:latest
    restart: unless-stopped
    ports:
      - 8800:80
    env_file:
      - $PWD/etc/simply_nzedb.conf
    volumes:
      - $PWD/data/covers:/var/www/nZEDb/resources/covers/
      - $PWD/data/nzb:/var/www/nZEDb/resources/nzb/
      - $PWD/data/tmp:/var/www/nZEDb/resources/tmp/unrar/
      # configuration/ is expected to contain
      #  - config.php
      #  - ircscraper_settings.php
      #  - settings.php
      #  - install.lock (only after setup has completed)
      - $PWD/data/configuration:/var/www/nZEDb/configuration/
      - $PWD/data/log/nginx-error.log:/var/log/nginx/nginx-error.log
      - $PWD/data/log/nginx-access.log:/var/log/nginx/access.log
      - $PWD/data/log/php-fpm.log:/var/log/php-fpm.log
      - $PWD/data/log/php_errors.log:/var/www/nZEDb/resources/logs/php_errors.log
      - $PWD/data/log/php_errors_web.log:/var/www/nZEDb/resources/logs/php_errors_web.log
      - $PWD/data/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/data/mytop:/root/.mytop
      - $PWD/data/predb_progress.txt:/var/www/nZEDb/cli/data/predb_progress.txt
      - $PWD/data/import:/var/www/nZEDb/resources/import/
      - $PWD/data/proxychains.conf:/etc/proxychains/proxychains.conf
      - $PWD/data/db_backups:/db_backups

  adminer:
    image: clue/adminer
    restart: unless-stopped
    ports:
      - 8880:80

  redis:
    image: redis:3.2.6-alpine
    restart: unless-stopped

  # manticore:
  #   image: manticoresearch/manticore:latest
  #   restart: unless-stopped
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #        soft: 65535
  #        hard: 65535
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - $PWD/data/manticore:/var/lib/manticore
  #     - $PWD/data/manticore.conf:/etc/manticoresearch/manticore.conf
  #     - $PWD/data/manticore/pid/:/var/run/sphinxsearch/
  #     - $PWD/data/manticore/logs/:/var/log/sphinxsearch/
  #     - $PWD/data/manticore/data:/var/lib/sphinxsearch/data/
  #     # - $PWD/data/sphinx/pid/:/var/run/sphinxsearch/
  #     # - $PWD/data/sphinx/logs/:/var/log/sphinxsearch/
  #     # - $PWD/data/sphinx/lib/:/var/lib/sphinxsearch/data/
  #   ports:
  #     - 127.0.0.1:9306:9306
  #     - 127.0.0.1:9308:9308


  sphinxsearch:
    image: thewillonline/nzedb-sphinxsearch:latest
    restart: unless-stopped
    volumes:
      - $PWD/data/sphinx/:/opt/sphinx/index
      - $PWD/data/sphinx.conf:/opt/sphinx/conf/sphinx.conf
      - $PWD/data/sphinx/pid/:/var/run/sphinxsearch/
      - $PWD/data/sphinx/logs/:/var/log/sphinxsearch/
      - $PWD/data/sphinx/lib/:/var/lib/sphinxsearch/data/
    ports:
      - 127.0.0.1:36307:36307
#      - 127.0.0.1:9312:9312
#      - 127.0.0.1:9306:9306
  #
  # znc:
  #   image: ghcr.io/linuxserver/znc
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Amsterdam
  #   volumes:
  #     - $PWD/data/znc/:/config
  #   ports:
  #     - 6501:6501
  #   restart: unless-stopped
