version: '2'
services:

  database:
    extends:
      file: common.yml
      service: database
    build: mariadb

  newznab:
    extends:
      file: common.yml
      service: nzedb
    build: nzedb
    links:
      - database
    depends_on:
      - database

  adminer:
    extends:
      file: common.yml
      service: adminer
    links:
      - database:db
    depends_on:
      - database

  sphinxsearch:
    extends:
      file: common.yml
      service: sphinxsearch
    links:
      - database
      - newznab
    depends_on:
      - database
      - newznab
